---@meta
---@diagnostic disable: missing-return, unused-local, duplicate-set-field

-- Generated by scripts/generate_epsilon_lib.py. Do not edit this file directly.
-- Epsilon Lua API definitions for Lua Language Server / EmmyLua.
-- This file is metadata only. Do not execute or require it from a script package.

---@alias EpsilonArgb integer
---@alias EpsilonDirection "down"|"up"|"north"|"south"|"west"|"east"
---@alias EpsilonJsonValue boolean|number|string|EpsilonJsonArray|EpsilonJsonObject
---@alias EpsilonEventId
---| "client_tick.pre"
---| "client_tick.post"
---| "packet.send"
---| "packet.receive"
---| "player_tick.pre"
---| "player_tick.post"
---| "render2d.level"
---| "render2d.hud"
---| "render3d"
---@alias EpsilonEventClassName
---| "AfterRender3DEvent"
---| "AttackEntityEvent"
---| "AttackSlowDownEvent"
---| "AttackYawEvent"
---| "BlockCollisionEvent"
---| "ChunkOcclusionEvent"
---| "ClientTickEvent.Pre"
---| "ClientTickEvent.Post"
---| "DestroyBlockEvent"
---| "FallFlyingEvent"
---| "FireworkRotationEvent"
---| "GameJoinedEvent"
---| "GameLeftEvent"
---| "JumpEvent"
---| "KeyboardInputEvent"
---| "KeyPressEvent"
---| "LevelUpdateEvent"
---| "MousePressEvent"
---| "MouseScrollEvent"
---| "MoveEvent"
---| "OpenScreenEvent"
---| "PacketEvent.Send"
---| "PacketEvent.Receive"
---| "PlayerTickEvent.Pre"
---| "PlayerTickEvent.Post"
---| "RaytraceEvent"
---| "Render2DEvent.Level"
---| "Render2DEvent.HUD"
---| "Render3DEvent"
---| "RespawnEvent"
---| "RightClickEvent"
---| "RotationAnimationEvent"
---| "SendPositionEvent"
---| "SlowdownEvent"
---| "StartDestroyBlockEvent"
---| "StartUseItemEvent"
---| "StrafeEvent"
---| "SwingHandEvent"
---| "TravelEvent"
---| "UseItemEvent"
---| "UseItemRaytraceEvent"

---@class EpsilonJsonArray: table<integer, EpsilonJsonValue>
---@class EpsilonJsonObject: table<string, EpsilonJsonValue>

---@class EpsilonLuaJava
local LuaJava = {}

---Binds a fully qualified Java class name.
---@param className string
---@return userdata javaClass
function LuaJava.bindClass(className) end

---Binds an Epsilon event class by its short registry name.
---@param eventName EpsilonEventClassName
---@return userdata javaClass
function LuaJava.bindEventClass(eventName) end

---Creates a Java object from a fully qualified class name.
---@param className string
---@param ... any
---@return userdata javaObject
function LuaJava.newInstance(className, ...) end

---Creates a Java object from a class returned by bindClass.
---@param javaClass userdata
---@param ... any
---@return userdata javaObject
LuaJava["new"] = function(javaClass, ...) end

---Creates a Java proxy. Interface names precede the implementation table.
---@param ... string|table
---@return userdata javaProxy
function LuaJava.createProxy(...) end

---Invokes a public static no-argument Java library loader.
---@param className string
---@param methodName string
---@return any
function LuaJava.loadLib(className, methodName) end

---@class EpsilonStorage
local Storage = {}

---Returns nil when the key does not exist.
---@param key string
---@return EpsilonJsonValue|nil value
function Storage:get(key) end

---Stores a JSON-compatible value. Use remove to delete a key.
---@param key string
---@param value EpsilonJsonValue
function Storage:set(key, value) end

---@param key string
function Storage:remove(key) end

function Storage:clear() end

---@class EpsilonSettingHandle<T>
---@field id string
---@field owner string
local SettingHandle = {}

---@return T value
function SettingHandle:get() end

---@param value T
---@return T normalizedValue
function SettingHandle:set(value) end

---@return userdata javaSetting
function SettingHandle:java_setting() end

---@class EpsilonSettingSpec
---@field id string Lowercase stable ID.
---@field group? string Group ID returned by group().
---@field available? fun(): boolean

---@class EpsilonBoolSettingSpec: EpsilonSettingSpec
---@field default boolean
---@field changed? fun(value: boolean)

---@class EpsilonIntSettingSpec: EpsilonSettingSpec
---@field default integer
---@field min integer
---@field max integer
---@field step integer
---@field changed? fun(value: integer)

---@class EpsilonDoubleSettingSpec: EpsilonSettingSpec
---@field default number
---@field min number
---@field max number
---@field step number
---@field changed? fun(value: number)

---@class EpsilonStringSettingSpec: EpsilonSettingSpec
---@field default string
---@field changed? fun(value: string)

---@class EpsilonChoiceSettingSpec: EpsilonSettingSpec
---@field default string
---@field choices string[]
---@field changed? fun(value: string)

---@class EpsilonColorSettingSpec: EpsilonSettingSpec
---@field default EpsilonArgb
---@field allowAlpha? boolean Defaults to true.

---@class EpsilonKeybindSettingSpec: EpsilonSettingSpec
---@field default integer GLFW key code.

---@class EpsilonStringListSettingSpec: EpsilonSettingSpec
---@field default string[]

---@class EpsilonSettingHostApi
local SettingHostApi = {}

---Declares a setting group. Only valid during an entrypoint's declaration phase.
---@param id string
---@return string groupId
function SettingHostApi:group(id) end

---Finds a setting already declared on this host.
---@param id string
---@return EpsilonSettingHandle<any>
function SettingHostApi:setting(id) end

---@param spec EpsilonBoolSettingSpec
---@return EpsilonSettingHandle<boolean>
function SettingHostApi:boolSetting(spec) end

---@param spec EpsilonIntSettingSpec
---@return EpsilonSettingHandle<integer>
function SettingHostApi:intSetting(spec) end

---@param spec EpsilonDoubleSettingSpec
---@return EpsilonSettingHandle<number>
function SettingHostApi:doubleSetting(spec) end

---@param spec EpsilonStringSettingSpec
---@return EpsilonSettingHandle<string>
function SettingHostApi:stringSetting(spec) end

---@param spec EpsilonChoiceSettingSpec
---@return EpsilonSettingHandle<string>
function SettingHostApi:choiceSetting(spec) end

---@param spec EpsilonColorSettingSpec
---@return EpsilonSettingHandle<EpsilonArgb>
function SettingHostApi:colorSetting(spec) end

---@param spec EpsilonKeybindSettingSpec
---@return EpsilonSettingHandle<integer>
function SettingHostApi:keybindSetting(spec) end

---@param spec EpsilonStringListSettingSpec
---@return EpsilonSettingHandle<string[]>
function SettingHostApi:stringListSetting(spec) end

---@class EpsilonAddonApi: EpsilonSettingHostApi
local AddonApi = {}

---@alias EpsilonEventCallback fun(event: userdata)
---@alias EpsilonRender2DCallback fun(ui: EpsilonUiContext, event: userdata)
---@alias EpsilonRender3DCallback fun(render3d: EpsilonRender3DContext, event: userdata)

---@class EpsilonModuleApi: EpsilonSettingHostApi
---@field readonly storage EpsilonStorage
local ModuleApi = {}

---@param callback fun()
function ModuleApi:on_enable(callback) end

---@param callback fun()
function ModuleApi:on_disable(callback) end

---@param callback fun()
function ModuleApi:on_cleanup(callback) end

---@overload fun(self: EpsilonModuleApi, eventId: "render2d.level"|"render2d.hud", priority: integer, callback: EpsilonRender2DCallback)
---@overload fun(self: EpsilonModuleApi, eventId: "render3d", priority: integer, callback: EpsilonRender3DCallback)
---@param eventId EpsilonEventId
---@param priority integer Render3D priorities must be greater than -999.
---@param callback EpsilonEventCallback
function ModuleApi:on(eventId, priority, callback) end

---@param eventClass userdata A class returned by luajava.bindEventClass or bindClass.
---@param priority integer Render3D priorities must be greater than -999.
---@param callback EpsilonEventCallback|EpsilonRender2DCallback|EpsilonRender3DCallback
function ModuleApi:on_class(eventClass, priority, callback) end

---@return userdata javaModule
function ModuleApi:java_module() end

---@class EpsilonPackageApi
---@field id string
---@field version string
---@field directory string
---@field packageStorage EpsilonStorage
local PackageApi = {}

---@class EpsilonUiContext
local UiContext = {}

---@param x number
---@param y number
---@param width number
---@param height number
---@param color EpsilonArgb
function UiContext:rect(x, y, width, height, color) end

---@param x number
---@param y number
---@param width number
---@param height number
---@param radius number
---@param color EpsilonArgb
function UiContext:round_rect(x, y, width, height, radius, color) end

---@param x number
---@param y number
---@param width number
---@param height number
---@param radius number
---@param thickness number
---@param color EpsilonArgb
function UiContext:outline(x, y, width, height, radius, thickness, color) end

---@param x number
---@param y number
---@param width number
---@param height number
---@param radius number
---@param blur number
---@param color EpsilonArgb
function UiContext:shadow(x, y, width, height, radius, blur, color) end

---@param text string
---@param x number
---@param y number
---@param scale number
---@param color EpsilonArgb
---@param font? string
function UiContext:text(text, x, y, scale, color, font) end

---Pass nil for font when using the default font with rotation.
---@param text string
---@param x number
---@param y number
---@param scale number
---@param color EpsilonArgb
---@param font string|nil
---@param angle number
---@param pivotX number
---@param pivotY number
function UiContext:rotated_text(text, x, y, scale, color, font, angle, pivotX, pivotY) end

---@param resource string
---@param x number
---@param y number
---@param width number
---@param height number
---@param color EpsilonArgb
function UiContext:texture(resource, x, y, width, height, color) end

---@param x number
---@param y number
---@param size number
---@param angle number
---@param color EpsilonArgb
function UiContext:triangle(x, y, size, angle, color) end

---@param layer integer
---@param callback fun(child: EpsilonUiContext)
function UiContext:layer(layer, callback) end

---@param x number
---@param y number
---@param width number
---@param height number
---@param callback fun(child: EpsilonUiContext)
function UiContext:scissor(x, y, width, height, callback) end

---@param x number
---@param y number
---@param width number
---@param height number
---@param callback fun(child: EpsilonUiContext)
function UiContext:push_absolute(x, y, width, height, callback) end

---@param text string
---@param scale number
---@param font? string
---@return number width
function UiContext:text_width(text, scale, font) end

---@param scale number
---@param font? string
---@return number height
function UiContext:text_height(scale, font) end

---@return userdata uiTreeScope
function UiContext:raw_scope() end

---@class EpsilonRender3DContext
local Render3DContext = {}

---@param box userdata A net.minecraft.world.phys.AABB.
---@param color EpsilonArgb
function Render3DContext:filled_box(box, color) end

---@param box userdata A net.minecraft.world.phys.AABB.
---@param bottomColor EpsilonArgb
---@param topColor EpsilonArgb
function Render3DContext:filled_fade_box(box, bottomColor, topColor) end

---@param box userdata A net.minecraft.world.phys.AABB.
---@param blurStrength number
function Render3DContext:blurred_box(box, blurStrength) end

---@param box userdata A net.minecraft.world.phys.AABB.
---@param color EpsilonArgb
---@param direction EpsilonDirection|userdata
function Render3DContext:filled_side(box, color, direction) end

---@param box userdata A net.minecraft.world.phys.AABB.
---@param color EpsilonArgb
---@param thickness number
function Render3DContext:outline_box(box, color, thickness) end

---@param box userdata A net.minecraft.world.phys.AABB.
---@param color EpsilonArgb
---@param thickness number
---@param direction EpsilonDirection|userdata
function Render3DContext:side_outline(box, color, thickness, direction) end

---@param from userdata A net.minecraft.world.phys.Vec3.
---@param to userdata A net.minecraft.world.phys.Vec3.
---@param color EpsilonArgb
---@param thickness number
function Render3DContext:line(from, to, color, thickness) end

---@param minX number
---@param minY number
---@param minZ number
---@param maxX number
---@param maxY number
---@param maxZ number
---@return userdata box A net.minecraft.world.phys.AABB.
function Render3DContext:box(minX, minY, minZ, maxX, maxY, maxZ) end

---@param x number
---@param y number
---@param z number
---@return userdata vector A net.minecraft.world.phys.Vec3.
function Render3DContext:vec3(x, y, z) end

---@return userdata scheduler A Render3DScheduler.
function Render3DContext:raw_scheduler() end

---@type EpsilonLuaJava
luajava = nil

---@type userdata net.minecraft.client.Minecraft
mc = nil

---Available in module entrypoints.
---@type EpsilonModuleApi
module = nil

---Declaration methods are only valid in settings.lua. Module entrypoints may call setting().
---@type EpsilonAddonApi
addon = nil

---@type EpsilonPackageApi
epsilon = nil
