#!/usr/bin/env python3
"""Generate the LuaLS metadata library for Epsilon's Java-backed Lua API."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
JAVA_ROOT = ROOT / "common" / "src" / "main" / "java" / "com" / "github" / "epsilon" / "scripting" / "lua"
DEFAULT_OUTPUT = ROOT / "docs" / "examples" / "lua" / "epsilon_lib.lua"

EVENT_ID_MARKER = "{{EVENT_IDS}}"
EVENT_CLASS_MARKER = "{{EVENT_CLASSES}}"

TEMPLATE = r'''---@meta
---@diagnostic disable: missing-return, unused-local, duplicate-set-field

-- Generated by scripts/generate_epsilon_lib.py. Do not edit this file directly.
-- Epsilon Lua API definitions for Lua Language Server / EmmyLua.
-- This file is metadata only. Do not execute or require it from a script package.

---@alias EpsilonArgb integer
---@alias EpsilonDirection "down"|"up"|"north"|"south"|"west"|"east"
---@alias EpsilonJsonValue boolean|number|string|EpsilonJsonArray|EpsilonJsonObject
---@alias EpsilonEventId
{{EVENT_IDS}}
---@alias EpsilonEventClassName
{{EVENT_CLASSES}}

---@class EpsilonJsonArray: table<integer, EpsilonJsonValue>
---@class EpsilonJsonObject: table<string, EpsilonJsonValue>

---@class EpsilonLuaJava
local LuaJava = {}

---Binds a fully qualified Java class name.
---@param className string
---@return userdata javaClass
function LuaJava.bindClass(className) end

---Binds an Epsilon event class by its short registry name.
---@param eventName EpsilonEventClassName
---@return userdata javaClass
function LuaJava.bindEventClass(eventName) end

---Creates a Java object from a fully qualified class name.
---@param className string
---@param ... any
---@return userdata javaObject
function LuaJava.newInstance(className, ...) end

---Creates a Java object from a class returned by bindClass.
---@param javaClass userdata
---@param ... any
---@return userdata javaObject
LuaJava["new"] = function(javaClass, ...) end

---Creates a Java proxy. Interface names precede the implementation table.
---@param ... string|table
---@return userdata javaProxy
function LuaJava.createProxy(...) end

---Invokes a public static no-argument Java library loader.
---@param className string
---@param methodName string
---@return any
function LuaJava.loadLib(className, methodName) end

---@class EpsilonStorage
local Storage = {}

---Returns nil when the key does not exist.
---@param key string
---@return EpsilonJsonValue|nil value
function Storage:get(key) end

---Stores a JSON-compatible value. Use remove to delete a key.
---@param key string
---@param value EpsilonJsonValue
function Storage:set(key, value) end

---@param key string
function Storage:remove(key) end

function Storage:clear() end

---@class EpsilonSettingHandle<T>
---@field id string
---@field owner string
local SettingHandle = {}

---@return T value
function SettingHandle:get() end

---@param value T
---@return T normalizedValue
function SettingHandle:set(value) end

---@return userdata javaSetting
function SettingHandle:java_setting() end

---@class EpsilonSettingSpec
---@field id string Lowercase stable ID.
---@field group? string Group ID returned by group().
---@field available? fun(): boolean

---@class EpsilonBoolSettingSpec: EpsilonSettingSpec
---@field default boolean
---@field changed? fun(value: boolean)

---@class EpsilonIntSettingSpec: EpsilonSettingSpec
---@field default integer
---@field min integer
---@field max integer
---@field step integer
---@field changed? fun(value: integer)

---@class EpsilonDoubleSettingSpec: EpsilonSettingSpec
---@field default number
---@field min number
---@field max number
---@field step number
---@field changed? fun(value: number)

---@class EpsilonStringSettingSpec: EpsilonSettingSpec
---@field default string
---@field changed? fun(value: string)

---@class EpsilonChoiceSettingSpec: EpsilonSettingSpec
---@field default string
---@field choices string[]
---@field changed? fun(value: string)

---@class EpsilonColorSettingSpec: EpsilonSettingSpec
---@field default EpsilonArgb
---@field allowAlpha? boolean Defaults to true.

---@class EpsilonKeybindSettingSpec: EpsilonSettingSpec
---@field default integer GLFW key code.

---@class EpsilonStringListSettingSpec: EpsilonSettingSpec
---@field default string[]

---@class EpsilonSettingHostApi
local SettingHostApi = {}

---Declares a setting group. Only valid during an entrypoint's declaration phase.
---@param id string
---@return string groupId
function SettingHostApi:group(id) end

---Finds a setting already declared on this host.
---@param id string
---@return EpsilonSettingHandle<any>
function SettingHostApi:setting(id) end

---@param spec EpsilonBoolSettingSpec
---@return EpsilonSettingHandle<boolean>
function SettingHostApi:boolSetting(spec) end

---@param spec EpsilonIntSettingSpec
---@return EpsilonSettingHandle<integer>
function SettingHostApi:intSetting(spec) end

---@param spec EpsilonDoubleSettingSpec
---@return EpsilonSettingHandle<number>
function SettingHostApi:doubleSetting(spec) end

---@param spec EpsilonStringSettingSpec
---@return EpsilonSettingHandle<string>
function SettingHostApi:stringSetting(spec) end

---@param spec EpsilonChoiceSettingSpec
---@return EpsilonSettingHandle<string>
function SettingHostApi:choiceSetting(spec) end

---@param spec EpsilonColorSettingSpec
---@return EpsilonSettingHandle<EpsilonArgb>
function SettingHostApi:colorSetting(spec) end

---@param spec EpsilonKeybindSettingSpec
---@return EpsilonSettingHandle<integer>
function SettingHostApi:keybindSetting(spec) end

---@param spec EpsilonStringListSettingSpec
---@return EpsilonSettingHandle<string[]>
function SettingHostApi:stringListSetting(spec) end

---@class EpsilonAddonApi: EpsilonSettingHostApi
local AddonApi = {}

---@alias EpsilonEventCallback fun(event: userdata)
---@alias EpsilonRender2DCallback fun(ui: EpsilonUiContext, event: userdata)
---@alias EpsilonRender3DCallback fun(render3d: EpsilonRender3DContext, event: userdata)

---@class EpsilonModuleApi: EpsilonSettingHostApi
---@field readonly storage EpsilonStorage
local ModuleApi = {}

---@param callback fun()
function ModuleApi:on_enable(callback) end

---@param callback fun()
function ModuleApi:on_disable(callback) end

---@param callback fun()
function ModuleApi:on_cleanup(callback) end

---@overload fun(self: EpsilonModuleApi, eventId: "render2d.level"|"render2d.hud", priority: integer, callback: EpsilonRender2DCallback)
---@overload fun(self: EpsilonModuleApi, eventId: "render3d", priority: integer, callback: EpsilonRender3DCallback)
---@param eventId EpsilonEventId
---@param priority integer Render3D priorities must be greater than -999.
---@param callback EpsilonEventCallback
function ModuleApi:on(eventId, priority, callback) end

---@param eventClass userdata A class returned by luajava.bindEventClass or bindClass.
---@param priority integer Render3D priorities must be greater than -999.
---@param callback EpsilonEventCallback|EpsilonRender2DCallback|EpsilonRender3DCallback
function ModuleApi:on_class(eventClass, priority, callback) end

---@return userdata javaModule
function ModuleApi:java_module() end

---@class EpsilonPackageApi
---@field id string
---@field version string
---@field directory string
---@field packageStorage EpsilonStorage
local PackageApi = {}

---@class EpsilonUiContext
local UiContext = {}

---@param x number
---@param y number
---@param width number
---@param height number
---@param color EpsilonArgb
function UiContext:rect(x, y, width, height, color) end

---@param x number
---@param y number
---@param width number
---@param height number
---@param radius number
---@param color EpsilonArgb
function UiContext:round_rect(x, y, width, height, radius, color) end

---@param x number
---@param y number
---@param width number
---@param height number
---@param radius number
---@param thickness number
---@param color EpsilonArgb
function UiContext:outline(x, y, width, height, radius, thickness, color) end

---@param x number
---@param y number
---@param width number
---@param height number
---@param radius number
---@param blur number
---@param color EpsilonArgb
function UiContext:shadow(x, y, width, height, radius, blur, color) end

---@param text string
---@param x number
---@param y number
---@param scale number
---@param color EpsilonArgb
---@param font? string
function UiContext:text(text, x, y, scale, color, font) end

---Pass nil for font when using the default font with rotation.
---@param text string
---@param x number
---@param y number
---@param scale number
---@param color EpsilonArgb
---@param font string|nil
---@param angle number
---@param pivotX number
---@param pivotY number
function UiContext:rotated_text(text, x, y, scale, color, font, angle, pivotX, pivotY) end

---@param resource string
---@param x number
---@param y number
---@param width number
---@param height number
---@param color EpsilonArgb
function UiContext:texture(resource, x, y, width, height, color) end

---@param x number
---@param y number
---@param size number
---@param angle number
---@param color EpsilonArgb
function UiContext:triangle(x, y, size, angle, color) end

---@param layer integer
---@param callback fun(child: EpsilonUiContext)
function UiContext:layer(layer, callback) end

---@param x number
---@param y number
---@param width number
---@param height number
---@param callback fun(child: EpsilonUiContext)
function UiContext:scissor(x, y, width, height, callback) end

---@param x number
---@param y number
---@param width number
---@param height number
---@param callback fun(child: EpsilonUiContext)
function UiContext:push_absolute(x, y, width, height, callback) end

---@param text string
---@param scale number
---@param font? string
---@return number width
function UiContext:text_width(text, scale, font) end

---@param scale number
---@param font? string
---@return number height
function UiContext:text_height(scale, font) end

---@return userdata uiTreeScope
function UiContext:raw_scope() end

---@class EpsilonRender3DContext
local Render3DContext = {}

---@param box userdata A net.minecraft.world.phys.AABB.
---@param color EpsilonArgb
function Render3DContext:filled_box(box, color) end

---@param box userdata A net.minecraft.world.phys.AABB.
---@param bottomColor EpsilonArgb
---@param topColor EpsilonArgb
function Render3DContext:filled_fade_box(box, bottomColor, topColor) end

---@param box userdata A net.minecraft.world.phys.AABB.
---@param blurStrength number
function Render3DContext:blurred_box(box, blurStrength) end

---@param box userdata A net.minecraft.world.phys.AABB.
---@param color EpsilonArgb
---@param direction EpsilonDirection|userdata
function Render3DContext:filled_side(box, color, direction) end

---@param box userdata A net.minecraft.world.phys.AABB.
---@param color EpsilonArgb
---@param thickness number
function Render3DContext:outline_box(box, color, thickness) end

---@param box userdata A net.minecraft.world.phys.AABB.
---@param color EpsilonArgb
---@param thickness number
---@param direction EpsilonDirection|userdata
function Render3DContext:side_outline(box, color, thickness, direction) end

---@param from userdata A net.minecraft.world.phys.Vec3.
---@param to userdata A net.minecraft.world.phys.Vec3.
---@param color EpsilonArgb
---@param thickness number
function Render3DContext:line(from, to, color, thickness) end

---@param minX number
---@param minY number
---@param minZ number
---@param maxX number
---@param maxY number
---@param maxZ number
---@return userdata box A net.minecraft.world.phys.AABB.
function Render3DContext:box(minX, minY, minZ, maxX, maxY, maxZ) end

---@param x number
---@param y number
---@param z number
---@return userdata vector A net.minecraft.world.phys.Vec3.
function Render3DContext:vec3(x, y, z) end

---@return userdata scheduler A Render3DScheduler.
function Render3DContext:raw_scheduler() end

---@type EpsilonLuaJava
luajava = nil

---@type userdata net.minecraft.client.Minecraft
mc = nil

---Available in module entrypoints.
---@type EpsilonModuleApi
module = nil

---Declaration methods are only valid in settings.lua. Module entrypoints may call setting().
---@type EpsilonAddonApi
addon = nil

---@type EpsilonPackageApi
epsilon = nil
'''


class GenerationError(RuntimeError):
    pass


def read_java(relative_path: str) -> str:
    path = JAVA_ROOT / relative_path
    try:
        return path.read_text(encoding="utf-8")
    except OSError as error:
        raise GenerationError(f"Cannot read Java source: {path}") from error


def extract_api_keys(relative_path: str) -> list[str]:
    source = read_java(relative_path)
    return re.findall(r'\bapi\.set\(\s*"([^"]+)"', source)


def extract_lua_methods(local_name: str) -> set[str]:
    pattern = rf'(?:function\s+{re.escape(local_name)}[:.]|{re.escape(local_name)}\["?)([A-Za-z_][A-Za-z0-9_]*)'
    return set(re.findall(pattern, TEMPLATE))


def verify_exports() -> None:
    documented = {
        "LuaStorage.java": extract_lua_methods("Storage"),
        "LuaSettingApi.java": extract_lua_methods("SettingHostApi"),
        "LuaModuleApi.java": extract_lua_methods("ModuleApi") | {"storage"},
        "render/LuaUiContext.java": extract_lua_methods("UiContext"),
        "render/LuaRender3DContext.java": extract_lua_methods("Render3DContext"),
        "LuaScriptPackage.java": {"id", "version", "directory", "packageStorage"},
    }
    for relative_path, documented_keys in documented.items():
        exported_keys = set(extract_api_keys(relative_path))
        if exported_keys != documented_keys:
            missing = sorted(exported_keys - documented_keys)
            stale = sorted(documented_keys - exported_keys)
            details = []
            if missing:
                details.append("missing metadata: " + ", ".join(missing))
            if stale:
                details.append("stale metadata: " + ", ".join(stale))
            raise GenerationError(f"Lua API drift in {relative_path}: {'; '.join(details)}")

    runtime_source = read_java("LuaRuntime.java")
    if 'luajava.set("bindEventClass"' not in runtime_source:
        raise GenerationError("LuaRuntime no longer exports luajava.bindEventClass")


def extract_events() -> tuple[list[str], list[str]]:
    source = read_java("event/LuaEventRegistry.java")
    class_names: list[str] = []
    event_ids: list[str] = []
    for match in re.finditer(r'\bregister\(\s*"([^"]+)"\s*,(?P<body>.*?)\);', source, re.DOTALL):
        class_name = match.group(1)
        strings = re.findall(r'"([^"]+)"', match.group(0))
        class_names.append(class_name)
        event_ids.extend(strings[1:])
    if not class_names:
        raise GenerationError("No event registrations found in LuaEventRegistry.java")
    return event_ids, class_names


def render_alias_values(values: list[str]) -> str:
    return "\n".join(f'---| "{value}"' for value in values)


def generate() -> str:
    verify_exports()
    event_ids, class_names = extract_events()
    generated = TEMPLATE.replace(EVENT_ID_MARKER, render_alias_values(event_ids))
    generated = generated.replace(EVENT_CLASS_MARKER, render_alias_values(class_names))
    return generated.rstrip() + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate docs/examples/lua/epsilon_lib.lua from the Java Lua API.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Output path for the generated Lua library.")
    parser.add_argument("--check", action="store_true", help="Fail when the output file is missing or out of date.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output = args.output.resolve()
    try:
        generated = generate()
    except GenerationError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    if args.check:
        try:
            current = output.read_text(encoding="utf-8")
        except OSError:
            current = None
        if current != generated:
            print(f"out of date: {output}", file=sys.stderr)
            print("run: python scripts/generate_epsilon_lib.py", file=sys.stderr)
            return 1
        print(f"up to date: {output}")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(generated, encoding="utf-8", newline="\n")
    print(f"generated: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
